### ISSUE TITLE
getToken private.url

### ISSUE THREAD

**Issue by ASKemp** [vperdigao/cf-graph#1]
The private.url in the getToken function, I assume that is not a generic value and needs to come from somewhere?

**Comment by vperdigao** [comment]
There is an example inside the method how the url should look:
<cfset private.url = "https://login.microsoftonline.com/e4388205-954b-4a6d-a178-4fc43ba71002/oauth2/v2.0/token">

At your Sharepoint dashboard you should be able to find your login url.

Can´t tell you exactly where because I don´t have a valid Sharepoint access anymore, sorry.
